### PR TITLE
Add none option to preset for laravel and symfony on js package manager

### PR DESCRIPTION
**Pull request by zarpelon**
| Issue | # |
| -----: | :-----: |
| :beetle: Bug Fix | No |
| :trophy: Feature | Yes |
| :pencil: Refactor | No |
| :open_book: Documentation | Yes/No |
| :warning: Break Change | No |

**Description**
Just add none option to js package manager
---

### CODE REVIEW

**Comment by fabriciojs** [comment]
Thank you @zarpelon !

In order for the changes you made to take effect, you need to run `kool run parse-presets` in your local environment and commit the modified files.

As we spoke on Slack, there is however an issue with `node-setup` script on `kool.yml`. For now, we are OK of having a new `no-js.yml` template that adds an empty `node-setup: echo "No JS"` script, so we don't break anything.

**Comment by ajmeireles** [comment]
> Thank you @zarpelon !
> 
> In order for the changes you made to take effect, you need to run `kool run parse-presets` in your local environment and commit the modified files.
> 
> As we spoke on Slack, there is however an issue with `node-setup` script on `kool.yml`. For now, we are OK of having a new `no-js.yml` template that adds an empty `node-setup: echo "No JS"` script, so we don't break anything.

Due to the long unanswered time, do you want me to open this same PR?

**Comment by fabriciojs** [comment]
@ajmeireles please feel free to take this one if you have time for it!

Just note my comment, there was a special case where we would end up with a weird (but currently necessary) "empty" `node-setup: echo "No JS" ` command. This is because our current reusability is not as flexible as we wanted to when putting presets together.

There is some WIP on #312 that I have been sitting on top of for several weeks now.

**Comment by fabriciojs** [comment]
Closing this due to inactivity. In case you still wanna work in the feedback suggested, please feel free to reopen this PR.

**Pull request closed without merging**
